# print(Mystr[8])
# print(Mystr[5])
# print(Mystr[8:14])
# print(Mystr[8:15])
# print(Mystr[3:7])
# print(Mystr[8:15:2])
# print(Mystr[::2])
# print(Mystr[-1])
# print(Mystr[-10])
Mystr="Hi I am Kristin"
# print(Mystr[-7:])
# print(Mystr[8:])
# print(Mystr[-12:])
# print(Mystr[:-12])
print(Mystr[-12::-1])